version: '3'


services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: www_docker_nginx
    volumes:
      - .:/docker
      # nginx.conf를 내가 만들지 않는다면 아래는 주석처리해도 된다.
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/logs:/etc/nginx/logs

    # 포트 지정. Host OS 의 포트를 Guest OS 로 연결
    ports:
      - "80:80"
      - "443:443"
     # PHP 의 기본 설정 파일은 컨테이너의 /usr/local/etc 에 있다.
  php:
    container_name: www_docker_php
    build:
      context: .
      dockerfile: Dockerfile.php # 별도의 Dockerfile 로 이미지를 생성하고, mysqli extension 설치를 하기 때문에, Dockerfile 로 작업한다.
    volumes:
      # nginx 설정과 같이 Host OS 의 /Users/thruthesky/www/docker 를 Guest OS 의 /docker 로 연결
      - .:/docker
      # Host OS 의 /Users/thruthesky/www/docker/etc/php.ini 를 Guest OS 의 /user/local/etc/php/php.ini 로 연결
      - ./etc/php.ini:/usr/local/etc/php/php.ini

  # MariaDB 설정
  # 주의: 각종 계정이나 루트 비번을 설정하면, DB 에 기록된다. 그래서 나중에 다시 변경하려면 DB 에서 변경을 해야 한다. 

volumes:
  mysqldata: {}