version: '3'


services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: www_docker_nginx
    volumes:
      - .:/docker
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/logs:/etc/nginx/logs

    # 포트 지정. Host OS 의 포트를 Guest OS 로 연결
    ports:
      - "80:80"
      - "443:443"

volumes:
  mysqldata: {}